# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-04 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0003_auto_20190304_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fantasia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
