# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-11 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0004_fantasia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Negra',
            new_name='Negra2',
        ),
    ]
