# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-11 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0005_auto_20190311_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Negra2',
            new_name='NovelaNegra',
        ),
    ]
