# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-11 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0006_auto_20190311_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NovelaNegra',
        ),
    ]
